// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: dpu-api/api.proto

package dpu_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFRequest) Reset() {
	*x = NFRequest{}
	mi := &file_dpu_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFRequest) ProtoMessage() {}

func (x *NFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpu_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFRequest.ProtoReflect.Descriptor instead.
func (*NFRequest) Descriptor() ([]byte, []int) {
	return file_dpu_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *NFRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *NFRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dpu_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dpu_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dpu_api_api_proto_rawDescGZIP(), []int{1}
}

var File_dpu_api_api_proto protoreflect.FileDescriptor

const file_dpu_api_api_proto_rawDesc = "" +
	"\n" +
	"\x11dpu-api/api.proto\x12\x06Vendor\"9\n" +
	"\tNFRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\a\n" +
	"\x05Empty2\x8e\x01\n" +
	"\x16NetworkFunctionService\x129\n" +
	"\x15CreateNetworkFunction\x12\x11.Vendor.NFRequest\x1a\r.Vendor.Empty\x129\n" +
	"\x15DeleteNetworkFunction\x12\x11.Vendor.NFRequest\x1a\r.Vendor.EmptyB/Z-github.com/openshift/dpu-operator/api/dpu-apib\x06proto3"

var (
	file_dpu_api_api_proto_rawDescOnce sync.Once
	file_dpu_api_api_proto_rawDescData []byte
)

func file_dpu_api_api_proto_rawDescGZIP() []byte {
	file_dpu_api_api_proto_rawDescOnce.Do(func() {
		file_dpu_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpu_api_api_proto_rawDesc), len(file_dpu_api_api_proto_rawDesc)))
	})
	return file_dpu_api_api_proto_rawDescData
}

var file_dpu_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dpu_api_api_proto_goTypes = []any{
	(*NFRequest)(nil), // 0: Vendor.NFRequest
	(*Empty)(nil),     // 1: Vendor.Empty
}
var file_dpu_api_api_proto_depIdxs = []int32{
	0, // 0: Vendor.NetworkFunctionService.CreateNetworkFunction:input_type -> Vendor.NFRequest
	0, // 1: Vendor.NetworkFunctionService.DeleteNetworkFunction:input_type -> Vendor.NFRequest
	1, // 2: Vendor.NetworkFunctionService.CreateNetworkFunction:output_type -> Vendor.Empty
	1, // 3: Vendor.NetworkFunctionService.DeleteNetworkFunction:output_type -> Vendor.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dpu_api_api_proto_init() }
func file_dpu_api_api_proto_init() {
	if File_dpu_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpu_api_api_proto_rawDesc), len(file_dpu_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dpu_api_api_proto_goTypes,
		DependencyIndexes: file_dpu_api_api_proto_depIdxs,
		MessageInfos:      file_dpu_api_api_proto_msgTypes,
	}.Build()
	File_dpu_api_api_proto = out.File
	file_dpu_api_api_proto_goTypes = nil
	file_dpu_api_api_proto_depIdxs = nil
}
