// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: dpu-api/api.proto

package dpu_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkFunctionService_CreateNetworkFunction_FullMethodName = "/Vendor.NetworkFunctionService/CreateNetworkFunction"
	NetworkFunctionService_DeleteNetworkFunction_FullMethodName = "/Vendor.NetworkFunctionService/DeleteNetworkFunction"
)

// NetworkFunctionServiceClient is the client API for NetworkFunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkFunctionServiceClient interface {
	CreateNetworkFunction(ctx context.Context, in *NFRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteNetworkFunction(ctx context.Context, in *NFRequest, opts ...grpc.CallOption) (*Empty, error)
}

type networkFunctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkFunctionServiceClient(cc grpc.ClientConnInterface) NetworkFunctionServiceClient {
	return &networkFunctionServiceClient{cc}
}

func (c *networkFunctionServiceClient) CreateNetworkFunction(ctx context.Context, in *NFRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NetworkFunctionService_CreateNetworkFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkFunctionServiceClient) DeleteNetworkFunction(ctx context.Context, in *NFRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NetworkFunctionService_DeleteNetworkFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkFunctionServiceServer is the server API for NetworkFunctionService service.
// All implementations must embed UnimplementedNetworkFunctionServiceServer
// for forward compatibility.
type NetworkFunctionServiceServer interface {
	CreateNetworkFunction(context.Context, *NFRequest) (*Empty, error)
	DeleteNetworkFunction(context.Context, *NFRequest) (*Empty, error)
	mustEmbedUnimplementedNetworkFunctionServiceServer()
}

// UnimplementedNetworkFunctionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkFunctionServiceServer struct{}

func (UnimplementedNetworkFunctionServiceServer) CreateNetworkFunction(context.Context, *NFRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetworkFunction not implemented")
}
func (UnimplementedNetworkFunctionServiceServer) DeleteNetworkFunction(context.Context, *NFRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNetworkFunction not implemented")
}
func (UnimplementedNetworkFunctionServiceServer) mustEmbedUnimplementedNetworkFunctionServiceServer() {
}
func (UnimplementedNetworkFunctionServiceServer) testEmbeddedByValue() {}

// UnsafeNetworkFunctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkFunctionServiceServer will
// result in compilation errors.
type UnsafeNetworkFunctionServiceServer interface {
	mustEmbedUnimplementedNetworkFunctionServiceServer()
}

func RegisterNetworkFunctionServiceServer(s grpc.ServiceRegistrar, srv NetworkFunctionServiceServer) {
	// If the following call pancis, it indicates UnimplementedNetworkFunctionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkFunctionService_ServiceDesc, srv)
}

func _NetworkFunctionService_CreateNetworkFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkFunctionServiceServer).CreateNetworkFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkFunctionService_CreateNetworkFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkFunctionServiceServer).CreateNetworkFunction(ctx, req.(*NFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkFunctionService_DeleteNetworkFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkFunctionServiceServer).DeleteNetworkFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkFunctionService_DeleteNetworkFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkFunctionServiceServer).DeleteNetworkFunction(ctx, req.(*NFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkFunctionService_ServiceDesc is the grpc.ServiceDesc for NetworkFunctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkFunctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Vendor.NetworkFunctionService",
	HandlerType: (*NetworkFunctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNetworkFunction",
			Handler:    _NetworkFunctionService_CreateNetworkFunction_Handler,
		},
		{
			MethodName: "DeleteNetworkFunction",
			Handler:    _NetworkFunctionService_DeleteNetworkFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dpu-api/api.proto",
}
